INSERT INTO `statistiche`.`squadra` (`nome`, `stadio`, `anno_fondazione`) VALUES ('atalanta', 'atleti azzuri d\'italia', '1907');
INSERT INTO `statistiche`.`squadra` (`nome`, `stadio`, `anno_fondazione`) VALUES ('benevento', 'ciro vigorito', '1929');
INSERT INTO `statistiche`.`squadra` (`nome`, `stadio`, `anno_fondazione`) VALUES ('bologna', 'renato dall\'ara', '1909');
INSERT INTO `statistiche`.`squadra` (`nome`, `stadio`, `anno_fondazione`) VALUES ('cagliari', 'sardegna arena', '1920');
INSERT INTO `statistiche`.`squadra` (`nome`, `stadio`, `anno_fondazione`) VALUES ('chievo', 'marcantonio bentegodi', '1929');
INSERT INTO `statistiche`.`squadra` (`nome`, `stadio`, `anno_fondazione`) VALUES ('crotone', 'ezio scida', '1910');
INSERT INTO `statistiche`.`squadra` (`nome`, `stadio`, `anno_fondazione`) VALUES ('fiorentina', 'artemio franchi', '1926');
INSERT INTO `statistiche`.`squadra` (`nome`, `stadio`, `anno_fondazione`) VALUES ('genoa', 'luigi ferraris', '1923');
INSERT INTO `statistiche`.`squadra` (`nome`, `stadio`, `anno_fondazione`) VALUES ('inter', 'giuseppe meazza', '1908');
INSERT INTO `statistiche`.`squadra` (`nome`, `stadio`, `anno_fondazione`) VALUES ('juventus', 'allianz stadium', '1897');
INSERT INTO `statistiche`.`squadra` (`nome`, `stadio`, `anno_fondazione`) VALUES ('lazio', 'olimpico', '1900');
INSERT INTO `statistiche`.`squadra` (`nome`, `stadio`, `anno_fondazione`) VALUES ('milan', 'giuseppe meazza', '1899');
INSERT INTO `statistiche`.`squadra` (`nome`, `stadio`, `anno_fondazione`) VALUES ('napoli', 'san paolo', '1926');
INSERT INTO `statistiche`.`squadra` (`nome`, `stadio`, `anno_fondazione`) VALUES ('roma', 'olimpico', '1927');
INSERT INTO `statistiche`.`squadra` (`nome`, `stadio`, `anno_fondazione`) VALUES ('sampdoria', 'luigi ferraris', '1946');
INSERT INTO `statistiche`.`squadra` (`nome`, `stadio`, `anno_fondazione`) VALUES ('sassuolo', 'mapei stadium', '1922');
INSERT INTO `statistiche`.`squadra` (`nome`, `stadio`, `anno_fondazione`) VALUES ('spal', 'paolo mazza', '1907');
INSERT INTO `statistiche`.`squadra` (`nome`, `stadio`, `anno_fondazione`) VALUES ('torino', 'olimpico', '1906');
INSERT INTO `statistiche`.`squadra` (`nome`, `stadio`, `anno_fondazione`) VALUES ('udinese', 'dacia arena', '1896');
INSERT INTO `statistiche`.`squadra` (`nome`, `stadio`, `anno_fondazione`) VALUES ('hellas verona', 'marcantonio bentegodi', '1903');
